name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_1:
    runs-on: ubuntu-latest
    steps:
      - name: test_1
        run: npm run test